### ISSUE TITLE
Support mapping the error value in #[span(err_lvl = "..")]

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#134]
When automatically completing spans based on the `Result` of their instrumented function, the `Err` variant is required to implement a trait which is effectively `&str | &(dyn Error + 'static) | (impl Error + 'static)`. This is an issue for types like `anyhow::Error` which is a very popular error handling strategy in applications, but doesn't satisfy any of those bounds.

We should add a new control parameter to the `#[span]` attribute called `err` that lets you map the error type. For `anyhow::Error`, you could then write something like:

```rust
#[emit::span(err: AsRef::<&(dyn Error + 'static)>::as_ref, "work")]
fn work() -> Result<(), anyhow::Error> {
    ..
}
```

The type accepted by `err` will be a `Fn(&E) -> U`, where `U` is expected to satisfy the `&str | &(dyn Error + 'static) | (imp Error + 'static)` bound.

**Comment by nblumhardt** [comment]
Placing this on every `#[emit::span..` usage seems like it could get noisy; I know coherence rules might get in the way - but is there any way applications could provide a trait implementation to get around this? Wracking my brain for some trick that might work.

Or otherwise, as a fallback, could something like `Display` be added to the set of acceptable types for `err`?
