### ISSUE TITLE
Remove Serde Dependency From Emit Core

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#39]
@nblumhardt has been talking about pulling that `serde` dependency out of the `emit` core. The only issue with this is that it makes it impossible to implement `serde::Serialize` for `emit` structures.

**Comment by nblumhardt** [comment]
:+1: one of the few big puzzle pieces remaining!

I don't think the `serde::Serialize` issue is likely to cause any problems; though one _might_ just serialize a whole `Event`, most of the time it'll be desirable to reformat it according to some external schema, in which case:

```rust
struct SerValue {
  value: Value
}

impl serde::Serialize for SerValue {
  // ...
}
```

...should be easy to insert into the structure, and won't (shouldn't) incur any runtime overhead.

For JSON serialization, just doing it by hand in `JsonFormatter` for `Value` would alternatively cover a lot of cases, and should be competitive with serde performance by virtue of being a lot more constrained/specific to just the case of `Value`. Any thoughts on how this would pan out?

**Comment by KodrAus** [comment]
My main concern with wrapping `Value` in a serialisable structure is that, unless I'm mistaken, you then need to build a new map to serialise a `BTreeMap<_, Value>` which isn't free and kind of a nuisance just to get around a design decision in the type system... Maybe we could pull `serde` out of `emit`, and then create a crate with a `SerdeFormatter` and do any hard work to efficiently build a serialisable structure from `Value` and maps of `Value`s in there?

That way other collectors in the future can use it too.

**Comment by nblumhardt** [comment]
Good point; implementing `SerdeFormatter` sounds like a better way to go.

What do you think about approaching this in two parts? Capturing was the original reason I piggy-backed the crate on Serde, with JSON formatting just being an opportunistic side-effect. I know we need to solve both problems in the one hit, but if we did our own capturing implementation and a simple hand-built JSON writer for value types, we might be able to do serde serialization as a second/independent PR?

(Only expecting that could work because all of the current serialization is JSON, but haven't looked deeply into how you are doing it in `emit_elasticsearch` so I may be missing the mark entirely - sorry :-) )
